// app/layout.tsx ou app/layout.ts selon ton projet
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import { AuthProvider } from "@/context/AuthContext";
import { MessageProvider } from "@/context/NotificationContext";
import MessageDisplay from "@/components/MessageDisplay";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider>

            <MessageProvider>
              <MessageDisplay />
              {children}
            </MessageProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
